version: 2

project_name: rssh

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/rssh
    binary: "rssh-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
      - android
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
      - mips64
      - mips64le
      - mips
      - mipsle
      - riscv64
      - ppc64le
      - s390x
      - loong64
    goarm:
      - "7"
      - "6"
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
      - goos: android
        goarch: arm
      - goos: android
        goarch: "386"
    hooks:
      post:
        - cmd: upx --best --lzma "{{ .Path }}" || true

archives:
  - format: binary
    name_template: "rssh-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: iprw
    name: rssh

changelog:
  use: github-native
